### ISSUE TITLE
Sky sphere has wrong render order

### ISSUE THREAD

**Issue by cryscan** [JonahPlusPlus/bevy_atmosphere#12]
![Examples Screenshot 2022 03 09 - 15 01 35 21](https://user-images.githubusercontent.com/16053640/157524264-d182f60f-b63f-4307-88ca-df525c19a498.png)
Sometimes the scene objects are rendered BEFORE the sky sphere, which makes them totally covered by it.
Posible solution: make the radius of sky sphere tunable.

**Comment by Shatur** [comment]
>  Posible solution: make the radius of sky sphere tunable.

Sounds reasonable to me. Could you send a PR for it?

**Comment by cryscan** [comment]
Sure! Will do.
