### ISSUE TITLE
Update for bevy main branch

### ISSUE THREAD

**Issue by MOZGIII** [JonahPlusPlus/bevy_atmosphere#2]
I'd like to check this plugin out with the latest bevy main from git (almost 0.6 afaik), and especially I'd like to check the directional light with this plugin.

Can we have a branch that updates to the latest bevy `main`? I'd use that directly for now, and it can be merged when bevy 0.6 ships.

**Comment by JonahPlusPlus** [comment]
Created it, but it has issues with conflicting packages. I'm currently taking a small break from Rust to focus more on a personal project, so feel free to try to fix this issue and make a pull request. I'll probably back to maintain/upgrade stuff for when 0.6 comes out.

**Comment by MOZGIII** [comment]
Things have changed significantly since 0.5 (last new related change happened yesterday actually).

I was unable to port the changes myself two days ago, I might be able to do it now :D
