### ISSUE TITLE
Custom skybox texture?

### ISSUE THREAD

**Issue by SeedyROM** [JonahPlusPlus/bevy_atmosphere#29]
Looking in the docs I see https://docs.rs/bevy_atmosphere/0.4.1/bevy_atmosphere/skybox/struct.SkyBoxMaterial.html which has a public field for the skybox texture. So I naively tried to just replace that texture with one of my own (obviously not going to work).

Is it possible to have a custom skybox?

**Comment by JonahPlusPlus** [comment]
I'll take a look at some code later, but I think it's possible, it's just not very streamlined right now. The `AtmospherePlugin` adds the `AtmospherePipelinePlugin` that renders to the `AtmosphereImage`. If you remove the plugin, you can use your own texture by manually creating a skybox with the skybox material (which you have to load in from the const handle handle yourself). It's basically everything inside `AtmospherePlugin` except for the pipeline code. Maybe I'll add a new feature to disable that part.
