### ISSUE TITLE
Support for `AtmosphereCamera` in child position

### ISSUE THREAD

**Issue by mbrc12** [JonahPlusPlus/bevy_atmosphere#40]
The following modification of `examples/basic.rs` seems to not work for me:

```rust
use bevy::prelude::*;
use bevy_atmosphere::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_plugin(AtmospherePlugin)
        .add_startup_system(setup)
        .run();
}

#[derive(Component)]
struct Player;

fn setup(mut commands: Commands) {
    commands.spawn(Player)
        .with_children(|p| {
            p.spawn((Camera3dBundle::default(), AtmosphereCamera::default()));
        });
}
```

Is it not supported to have `AtmosphereCamera` as a child? Having the `Camera` as a child is often useful because it inherits the transforms of the parent `Player`. I am open to suggestions on how to better structure this if not supporting this is intentional.

**Comment by JonahPlusPlus** [comment]
Bevy gives you a couple warnings:
```
2023-01-02T19:09:10.061343Z  WARN bevy_hierarchy::valid_parent_check_plugin: warning[B0004]: An entity with the GlobalTransform component has a parent without GlobalTransform.
This will cause inconsistent behaviors! See https://bevyengine.org/learn/errors/#B0004
2023-01-02T19:09:10.061346Z  WARN bevy_hierarchy::valid_parent_check_plugin: warning[B0004]: An entity with the ComputedVisibility component has a parent without ComputedVisibility.
This will cause inconsistent behaviors! See https://bevyengine.org/learn/errors/#B0004
```

To see the atmosphere, you just need to add a [`VisibilityBundle`](https://docs.rs/bevy/latest/bevy/prelude/struct.VisibilityBundle.html) to your parent.

If you are going to move your player around, you also want a [`TransformBundle`](https://docs.rs/bevy/latest/bevy/prelude/struct.TransformBundle.html).

Instead of adding both these bundles, you can just add a [`SpatialBundle`](https://docs.rs/bevy/latest/bevy/prelude/struct.SpatialBundle.html):

```rust
use bevy::prelude::*;
use bevy_atmosphere::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_plugin(AtmospherePlugin)
        .add_startup_system(setup)
        .run();
}

#[derive(Component)]
struct Player;

fn setup(mut commands: Commands) {
    commands.spawn(Player)
	.insert(SpatialBundle::default())
        .with_children(|p| {
            p.spawn((Camera3dBundle::default(), AtmosphereCamera::default()));
        });
}
```

**Comment by mbrc12** [comment]
I see, thanks for pointing that out! Surprisingly, `bevy` does not show that warning in `--release` mode, which is what I was using, but does show it in `--debug` mode.

**Comment by JonahPlusPlus** [comment]
Ah, interesting. I've never noticed that. I recommend reading more about Bevy's [visiblity system](https://bevy-cheatbook.github.io/features/visibility.html). You're not the first person to be tripped up by it (I should make it part of an FAQ).
