### ISSUE TITLE
Current Wasm advice is misleading

### ISSUE THREAD

**Issue by janhohenheim** [JonahPlusPlus/bevy_atmosphere#43]
The current advice about activating a feature flag in the browser for WebGPU is not sufficient to actually use WebGPU in Bevy, since Bevy forces wgpu to use WebGL. One actually needs to depend on a fork of Bevy to run WebGPU, sadly.
I'm reporting this because I happen to have lost time to this in the past for another crate and want others not to have to dig too deep :)

**Comment by JonahPlusPlus** [comment]
I see, thanks for bringing this to my attention. I'll make sure to fix this in the next update.

**Comment by JonahPlusPlus** [comment]
Okay, I think the new info is sufficient. Thank you for reporting this.
