### ISSUE TITLE
Sky doesn't work

### ISSUE THREAD

**Issue by VirxEC** [JonahPlusPlus/bevy_atmosphere#64]
When I updated to the new 0.8 version, I get the error `ERROR bevy_asset::server: path not found: bevy_atmosphere/shaders/skybox.wgsl` Which is weird because this plugin used to work when I was testing it earlier on the PR fork and I dropped a comment saying that it worked fine.

**Comment by Shatur** [comment]
Interesting, looks like it works locally (examples still work!), but doesn't work if it's a crate. @sphw maybe you know what could cause it?

**Comment by sphw** [comment]
My best guess is this is something to do with a bug with `embedded_asset` and publish crates / libraries. Not exactly sure what. IMO given all the strangeness and bugs with `embedded_asset` it might make sense to revert the commit that makes that change from my PR, and wait until it stabilizes further.

**Comment by Shatur** [comment]
Agree, could you please open a PR that reverts to the previous approach?

**Comment by Shatur** [comment]
Fixed by #65.
