### ISSUE TITLE
Rendering is slow in dymanic mode

### ISSUE THREAD

**Issue by djeedai** [JonahPlusPlus/bevy_atmosphere#7]
It seems the material buffer is re-created each frame, instead of being reused and only the new content re-uploaded if necessary:
https://github.com/JonahPlusPlus/bevy_atmosphere/blob/f85f3a5414862b077164ef8225f1e02ff578fa6d/src/material.rs#L123-L131

On a beefy developer machine I see some ~22ms frame time with `bevy_atmosphere`, a single cube, and a single tiny UI text showing the FPS. On a more mid-range laptop config this climbs to >50ms. Not sure this create buffer is the cause but it likely doesn't help.

**Comment by Shatur** [comment]
> It seems the material buffer is re-created each frame, instead of being reused and only the new content re-uploaded if necessary:

Are you sure that this function is called every frame? Have you profiled it? I thought that this function is called only on material creation.

**Comment by djeedai** [comment]
It is if you use dynamic mode.

![image](https://user-images.githubusercontent.com/6532395/157099117-31e165f2-7f51-410e-871b-4a9a7f552329.png)

**Comment by Shatur** [comment]
Oh, right, it changing dynamic mode. But are we able to skip asset preparation for every frame?

**Comment by djeedai** [comment]
Asset preparation, no, you can't skip it. You need to update the material's uniform each time the CPU material changes. But that doesn't mean that you need to create a new GPU buffer for it each time. I think you should instead create a GPU buffer once, and only update it in the prepare phase. So the `create_bind_group()` call is expected; that's why I didn't link it. But I'd expect to see here a GPU buffer update (_e.g._ [`Queue::writer_buffer()`](https://docs.rs/wgpu/latest/wgpu/struct.Queue.html#method.write_buffer), or using a Bevy utility like [`UniformVec::write_buffer()`](https://docs.rs/bevy/latest/bevy/render/render_resource/struct.UniformVec.html#method.write_buffer)), not a new buffer creation. As far as I know the former is a _lot_ cheaper than the latter, though I admit I didn't profile that change.

**Comment by Shatur** [comment]
Thanks, I get it now!
But we move `buffer` and `bind_group` later into `GpuAtmosphereMat`. Are we able to access previous `GpuAtmosphereMat`?

**Comment by djeedai** [comment]
Yes in theory the prepare phase is operating on the render world only so would have access to any render resource like `GpuAtmosphereMat`. See the [description of the `Prepare` phase](https://docs.rs/bevy/latest/bevy/render/enum.RenderStage.html#variant.Prepare) in the docs:
> Prepare render resources from the extracted data for the GPU.

I _think_ you need to add an `SQuery<&mut GpuAtmosphereMat>` to your system params (`type Param = ...`).

**Comment by Shatur** [comment]
I think we could close this?

**Comment by djeedai** [comment]
Can we? I didn't try again, but did the initializing of resources moved out of the hot loop?

**Comment by Shatur** [comment]
Yep, the plugin was rewritten: https://github.com/JonahPlusPlus/bevy_atmosphere/issues/18

**Comment by djeedai** [comment]
Then yes that issue is likely irrelevant anymore.
